/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;
import controlador.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import modelo.Huesped;

/**
 *
 * @author Danis
 */
public class frmPrincipal extends javax.swing.JFrame {
    
    private ControladorHuespedes controladorHuespedes;

    /**
     * Creates new form Vistappal
     */
    public frmPrincipal() {
        initComponents();
        ControladorHuespedes controlador = new ControladorHuespedes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlHuespedes = new javax.swing.JPanel();
        txtDocumentoHuesped = new javax.swing.JTextField();
        lblDocumentoHuesped = new javax.swing.JLabel();
        txtNombreHuesped = new javax.swing.JTextField();
        lblNombreHuesped = new javax.swing.JLabel();
        lblApellidoHuesped = new javax.swing.JLabel();
        txtApellidoHuesped = new javax.swing.JTextField();
        lblEmailHuesped = new javax.swing.JLabel();
        txtEmailHuesped = new javax.swing.JTextField();
        btnCrearHuesped = new javax.swing.JButton();
        btnBuscarHuesped = new javax.swing.JButton();
        btnActualizarHuesped = new javax.swing.JButton();
        btnEliminarHuesped = new javax.swing.JButton();
        lblNacionalidadHuesped = new javax.swing.JLabel();
        txtNacionalidadHuesped = new javax.swing.JTextField();
        cbxDiaNacimientoHuesped = new javax.swing.JComboBox<>();
        lblDiaNacimientoHuesped = new javax.swing.JLabel();
        lblMesNacimientoHuesped = new javax.swing.JLabel();
        cbxMesNacimientoHuesped = new javax.swing.JComboBox<>();
        lblAnioNacimientoHuesped = new javax.swing.JLabel();
        cbxAnioNacimientoHuesped = new javax.swing.JComboBox<>();
        lblFechaNacimientoHuesped = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        lblTituloPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDocumentoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoHuespedActionPerformed(evt);
            }
        });

        lblDocumentoHuesped.setText("Documento");

        txtNombreHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHuespedActionPerformed(evt);
            }
        });

        lblNombreHuesped.setText("Nombre");

        lblApellidoHuesped.setText("Apellido");

        lblEmailHuesped.setText("Email");

        btnCrearHuesped.setText("Crear");
        btnCrearHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearHuespedActionPerformed(evt);
            }
        });

        btnBuscarHuesped.setText("Buscar");

        btnActualizarHuesped.setText("Actualizar");

        btnEliminarHuesped.setText("Eliminar");

        lblNacionalidadHuesped.setText("Nacionalidad");

        cbxDiaNacimientoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaNacimientoHuespedActionPerformed(evt);
            }
        });

        lblDiaNacimientoHuesped.setText("Dia");

        lblMesNacimientoHuesped.setText("Mes");

        cbxMesNacimientoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesNacimientoHuespedActionPerformed(evt);
            }
        });

        lblAnioNacimientoHuesped.setText("Año");

        lblFechaNacimientoHuesped.setText("Fecha de nacimiento");

        javax.swing.GroupLayout pnlHuespedesLayout = new javax.swing.GroupLayout(pnlHuespedes);
        pnlHuespedes.setLayout(pnlHuespedesLayout);
        pnlHuespedesLayout.setHorizontalGroup(
            pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuespedesLayout.createSequentialGroup()
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHuespedesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                .addComponent(btnCrearHuesped)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarHuesped)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarHuesped)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarHuesped))
                            .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                    .addComponent(lblDiaNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxDiaNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                            .addComponent(lblMesNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbxMesNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblAnioNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblFechaNacimientoHuesped))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxAnioNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                    .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombreHuesped))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                            .addComponent(txtNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblApellidoHuesped)
                                            .addGap(46, 46, 46)
                                            .addComponent(txtApellidoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                            .addComponent(txtEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblNacionalidadHuesped)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNacionalidadHuesped)))))))
                    .addGroup(pnlHuespedesLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblDocumentoHuesped)
                        .addGap(18, 18, 18)
                        .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        pnlHuespedesLayout.setVerticalGroup(
            pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuespedesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearHuesped)
                    .addComponent(btnBuscarHuesped)
                    .addComponent(btnActualizarHuesped)
                    .addComponent(btnEliminarHuesped))
                .addGap(18, 18, 18)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentoHuesped)
                    .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreHuesped)
                    .addComponent(txtNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoHuesped)
                    .addComponent(txtApellidoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailHuesped)
                    .addComponent(txtEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNacionalidadHuesped)
                    .addComponent(txtNacionalidadHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(lblFechaNacimientoHuesped)
                .addGap(18, 18, 18)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaNacimientoHuesped)
                    .addComponent(cbxDiaNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesNacimientoHuesped)
                    .addComponent(cbxMesNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnioNacimientoHuesped)
                    .addComponent(cbxAnioNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("Huespedes", pnlHuespedes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 267, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("Habitaciones", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        pnlPrincipal.addTab("Reservas", jPanel4);

        lblTituloPrincipal.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("Hotel Imperial 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(lblTituloPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblTituloPrincipal)
                .addGap(18, 18, 18)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoHuespedActionPerformed

    private void txtNombreHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHuespedActionPerformed

    private void btnCrearHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearHuespedActionPerformed
        // TODO add your handling code here:
           crearHuesped();

    }//GEN-LAST:event_btnCrearHuespedActionPerformed

    private void cbxDiaNacimientoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaNacimientoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaNacimientoHuespedActionPerformed

    private void cbxMesNacimientoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesNacimientoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesNacimientoHuespedActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHuesped;
    private javax.swing.JButton btnBuscarHuesped;
    private javax.swing.JButton btnCrearHuesped;
    private javax.swing.JButton btnEliminarHuesped;
    private javax.swing.JComboBox<String> cbxAnioNacimientoHuesped;
    private javax.swing.JComboBox<String> cbxDiaNacimientoHuesped;
    private javax.swing.JComboBox<String> cbxMesNacimientoHuesped;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblAnioNacimientoHuesped;
    private javax.swing.JLabel lblApellidoHuesped;
    private javax.swing.JLabel lblDiaNacimientoHuesped;
    private javax.swing.JLabel lblDocumentoHuesped;
    private javax.swing.JLabel lblEmailHuesped;
    private javax.swing.JLabel lblFechaNacimientoHuesped;
    private javax.swing.JLabel lblMesNacimientoHuesped;
    private javax.swing.JLabel lblNacionalidadHuesped;
    private javax.swing.JLabel lblNombreHuesped;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JPanel pnlHuespedes;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JTextField txtApellidoHuesped;
    private javax.swing.JTextField txtDocumentoHuesped;
    private javax.swing.JTextField txtEmailHuesped;
    private javax.swing.JTextField txtNacionalidadHuesped;
    private javax.swing.JTextField txtNombreHuesped;
    // End of variables declaration//GEN-END:variables



 public boolean validarCamposHuesped() {
        if (txtDocumentoHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El documento es obligatorio");
            return false;
        } else if (txtNombreHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
            return false;
        } else if (txtEmailHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El correo es obligatorio");
            return false;
        } else if (txtApellidoHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El apellido es obligatorio");
            return false;
        } else if (txtNacionalidadHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La nacionalidad es obligatoria");
            return false;
        } else {
            return true;
        }
    }

    private void crearHuesped() {
        if (validarCamposHuesped()) {
            
            String documento = txtDocumentoHuesped.getText();
            String nombre = txtNombreHuesped.getText();
            String apellido = txtApellidoHuesped.getText();
            String email = txtEmailHuesped.getText();
            String nacionalidad = txtNacionalidadHuesped.getText();
            int diaNacimiento = Integer.parseInt(cbxDiaNacimientoHuesped.getSelectedItem().toString());
            int mesNacimiento = Integer.parseInt(cbxMesNacimientoHuesped.getSelectedItem().toString());
            int anioNacimiento = Integer.parseInt(cbxAnioNacimientoHuesped.getSelectedItem().toString());
            
            
            Huesped huesped =
        controladorHuespedes.crearHuesped(documento,nombre,apellido,email,
                nacionalidad,diaNacimiento,mesNacimiento, anioNacimiento);
                    
            if (huesped != null) {
                JOptionPane.showMessageDialog(this, "Cliente creado correctamente...");
                System.out.println(huesped.getDocumento() + " - " + huesped.getNombre());
                limpiarCamposCliente();
            } else {
                JOptionPane.showMessageDialog(this, "Error al crear el cliente... Puede que ya exista.");
            }
        }
        
    }
    
    private void limpiarCamposCliente() {
        txtDocumentoHuesped.setText("");
        txtNombreHuesped.setText("");
        txtEmailHuesped.setText("");
        txtApellidoHuesped.setText("");
        txtNacionalidadHuesped.setText("");
        cbxDiaNacimientoHuesped.setSelectedIndex(0);
        cbxMesNacimientoHuesped.setSelectedIndex(0);
        cbxAnioNacimientoHuesped.setSelectedIndex(0);
}
    private void llenarCombos() {
        // Día de nacimiento
        for (int i = 31; i >= 1; i--) {
            cbxDiaNacimientoHuesped.addItem(i + "");
        }
        
        // Mes de nacimiento
        for (int i = 12; i >= 1; i--) {
            cbxMesNacimientoHuesped.addItem(i + "");
        }
        
        // Año de nacimiento
        for (int i = LocalDate.now().getYear(); i >= 1940; i--) {
            cbxAnioNacimientoHuesped.addItem(i + "");
        }
    }
    
}