/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package vista;

import controlador.*;
import java.time.LocalDate;
import javax.swing.JOptionPane;
import modelo.*;

/**
 *
 * @author Danis
 */
public class frmPrincipal extends javax.swing.JFrame {

    ControladorHuespedes Ctrhuespedes;
    ControladorHabitaciones Ctrhabitaciones;

    /**
     * Creates new form Vistappal
     */
    public frmPrincipal() {
        initComponents();
        Ctrhuespedes = new ControladorHuespedes();
        Ctrhabitaciones = new ControladorHabitaciones(Ctrhuespedes.getHotel());
        llenarCombos();
        actualizarCbxHabitaciones();

        pnlPrincipal.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                if (pnlPrincipal.getSelectedIndex() == 1) {
                    actualizarCbxHuespedes();
                    actualizarTablaHabitaciones();
                }
            }
        });

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlPrincipal = new javax.swing.JTabbedPane();
        pnlHuespedes = new javax.swing.JPanel();
        txtDocumentoHuesped = new javax.swing.JTextField();
        lblDocumentoHuesped = new javax.swing.JLabel();
        txtNombreHuesped = new javax.swing.JTextField();
        lblNombreHuesped = new javax.swing.JLabel();
        lblApellidoHuesped = new javax.swing.JLabel();
        txtApellidoHuesped = new javax.swing.JTextField();
        lblEmailHuesped = new javax.swing.JLabel();
        txtEmailHuesped = new javax.swing.JTextField();
        btnCrearHuesped = new javax.swing.JButton();
        btnBuscarHuesped = new javax.swing.JButton();
        btnActualizarHuesped = new javax.swing.JButton();
        btnEliminarHuesped = new javax.swing.JButton();
        lblNacionalidadHuesped = new javax.swing.JLabel();
        txtNacionalidadHuesped = new javax.swing.JTextField();
        cbxDiaNacimientoHuesped = new javax.swing.JComboBox<>();
        lblDiaNacimientoHuesped = new javax.swing.JLabel();
        lblMesNacimientoHuesped = new javax.swing.JLabel();
        cbxMesNacimientoHuesped = new javax.swing.JComboBox<>();
        lblAnioNacimientoHuesped = new javax.swing.JLabel();
        cbxAnioNacimientoHuesped = new javax.swing.JComboBox<>();
        lblFechaNacimientoHuesped = new javax.swing.JLabel();
        pnlHabitaciones = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        lblNumeroHabitacion = new javax.swing.JLabel();
        lblHabitacionDisponible = new javax.swing.JLabel();
        btnAsignarHabitacion = new javax.swing.JButton();
        cbxHuespedes = new javax.swing.JComboBox<>();
        txtHabitacionDisponible = new javax.swing.JTextField();
        lblHuespedes = new javax.swing.JLabel();
        btnCancelarHabitacion = new javax.swing.JButton();
        cbxHabitaciones = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlReservas = new javax.swing.JPanel();
        lblTituloPrincipal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDocumentoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDocumentoHuespedActionPerformed(evt);
            }
        });

        lblDocumentoHuesped.setText("Documento");

        txtNombreHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreHuespedActionPerformed(evt);
            }
        });

        lblNombreHuesped.setText("Nombre");

        lblApellidoHuesped.setText("Apellido");

        lblEmailHuesped.setText("Email");

        btnCrearHuesped.setText("Crear");
        btnCrearHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearHuespedActionPerformed(evt);
            }
        });

        btnBuscarHuesped.setText("Buscar");
        btnBuscarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarHuespedActionPerformed(evt);
            }
        });

        btnActualizarHuesped.setText("Actualizar");
        btnActualizarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarHuespedActionPerformed(evt);
            }
        });

        btnEliminarHuesped.setText("Eliminar");
        btnEliminarHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarHuespedActionPerformed(evt);
            }
        });

        lblNacionalidadHuesped.setText("Nacionalidad");

        cbxDiaNacimientoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxDiaNacimientoHuespedActionPerformed(evt);
            }
        });

        lblDiaNacimientoHuesped.setText("Dia");

        lblMesNacimientoHuesped.setText("Mes");

        cbxMesNacimientoHuesped.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMesNacimientoHuespedActionPerformed(evt);
            }
        });

        lblAnioNacimientoHuesped.setText("Año");

        lblFechaNacimientoHuesped.setText("Fecha de nacimiento");

        javax.swing.GroupLayout pnlHuespedesLayout = new javax.swing.GroupLayout(pnlHuespedes);
        pnlHuespedes.setLayout(pnlHuespedesLayout);
        pnlHuespedesLayout.setHorizontalGroup(
            pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuespedesLayout.createSequentialGroup()
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHuespedesLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                .addComponent(btnCrearHuesped)
                                .addGap(18, 18, 18)
                                .addComponent(btnBuscarHuesped)
                                .addGap(18, 18, 18)
                                .addComponent(btnActualizarHuesped)
                                .addGap(18, 18, 18)
                                .addComponent(btnEliminarHuesped))
                            .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                    .addComponent(lblDiaNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(cbxDiaNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                            .addComponent(lblMesNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(cbxMesNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addGap(18, 18, 18)
                                            .addComponent(lblAnioNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addComponent(lblFechaNacimientoHuesped))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbxAnioNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                    .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNombreHuesped))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                            .addComponent(txtNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblApellidoHuesped)
                                            .addGap(46, 46, 46)
                                            .addComponent(txtApellidoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(pnlHuespedesLayout.createSequentialGroup()
                                            .addComponent(txtEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(lblNacionalidadHuesped)
                                            .addGap(18, 18, 18)
                                            .addComponent(txtNacionalidadHuesped)))))))
                    .addGroup(pnlHuespedesLayout.createSequentialGroup()
                        .addGap(185, 185, 185)
                        .addComponent(lblDocumentoHuesped)
                        .addGap(18, 18, 18)
                        .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(222, Short.MAX_VALUE))
        );
        pnlHuespedesLayout.setVerticalGroup(
            pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHuespedesLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearHuesped)
                    .addComponent(btnBuscarHuesped)
                    .addComponent(btnActualizarHuesped)
                    .addComponent(btnEliminarHuesped))
                .addGap(18, 18, 18)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDocumentoHuesped)
                    .addComponent(txtDocumentoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreHuesped)
                    .addComponent(txtNombreHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblApellidoHuesped)
                    .addComponent(txtApellidoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblEmailHuesped)
                    .addComponent(txtEmailHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNacionalidadHuesped)
                    .addComponent(txtNacionalidadHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addComponent(lblFechaNacimientoHuesped)
                .addGap(18, 18, 18)
                .addGroup(pnlHuespedesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDiaNacimientoHuesped)
                    .addComponent(cbxDiaNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblMesNacimientoHuesped)
                    .addComponent(cbxMesNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAnioNacimientoHuesped)
                    .addComponent(cbxAnioNacimientoHuesped, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(91, Short.MAX_VALUE))
        );

        pnlPrincipal.addTab("Huespedes", pnlHuespedes);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        lblNumeroHabitacion.setText("Habitaciones");

        lblHabitacionDisponible.setText("Habitación disponible");

        btnAsignarHabitacion.setText("Asignar");
        btnAsignarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAsignarHabitacionActionPerformed(evt);
            }
        });

        cbxHuespedes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblHuespedes.setText("Huesped");

        btnCancelarHabitacion.setText("Liberar");
        btnCancelarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarHabitacionActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlHabitacionesLayout = new javax.swing.GroupLayout(pnlHabitaciones);
        pnlHabitaciones.setLayout(pnlHabitacionesLayout);
        pnlHabitacionesLayout.setHorizontalGroup(
            pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                                .addComponent(btnAsignarHabitacion)
                                .addGap(18, 18, 18)
                                .addComponent(btnCancelarHabitacion))
                            .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                                .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblNumeroHabitacion)
                                    .addComponent(lblHabitacionDisponible))
                                .addGap(18, 18, 18)
                                .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                                        .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(cbxHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(txtHabitacionDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(cbxHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 418, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addComponent(lblHuespedes)))
                .addContainerGap(338, Short.MAX_VALUE))
        );
        pnlHabitacionesLayout.setVerticalGroup(
            pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlHabitacionesLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNumeroHabitacion)
                            .addComponent(cbxHabitaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblHabitacionDisponible)
                            .addComponent(txtHabitacionDisponible, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(18, 18, 18)
                .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblHuespedes)
                    .addComponent(cbxHuespedes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlHabitacionesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAsignarHabitacion)
                    .addComponent(btnCancelarHabitacion))
                .addGap(49, 49, 49))
        );

        pnlPrincipal.addTab("Habitaciones", pnlHabitaciones);

        javax.swing.GroupLayout pnlReservasLayout = new javax.swing.GroupLayout(pnlReservas);
        pnlReservas.setLayout(pnlReservasLayout);
        pnlReservasLayout.setHorizontalGroup(
            pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 826, Short.MAX_VALUE)
        );
        pnlReservasLayout.setVerticalGroup(
            pnlReservasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 367, Short.MAX_VALUE)
        );

        pnlPrincipal.addTab("Reservas", pnlReservas);

        lblTituloPrincipal.setFont(new java.awt.Font("SansSerif", 1, 36)); // NOI18N
        lblTituloPrincipal.setText("Hotel Imperial 2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlPrincipal)
            .addGroup(layout.createSequentialGroup()
                .addGap(279, 279, 279)
                .addComponent(lblTituloPrincipal)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(27, Short.MAX_VALUE)
                .addComponent(lblTituloPrincipal)
                .addGap(18, 18, 18)
                .addComponent(pnlPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 398, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDocumentoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDocumentoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDocumentoHuespedActionPerformed

    private void txtNombreHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreHuespedActionPerformed

    private void btnCrearHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearHuespedActionPerformed
        // TODO add your handling code here:
        crearHuesped();

    }//GEN-LAST:event_btnCrearHuespedActionPerformed

    private void cbxDiaNacimientoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxDiaNacimientoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxDiaNacimientoHuespedActionPerformed

    private void cbxMesNacimientoHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMesNacimientoHuespedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxMesNacimientoHuespedActionPerformed

    private void btnBuscarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarHuespedActionPerformed
        // TODO add your handling code here:
        buscarHuesped();
    }//GEN-LAST:event_btnBuscarHuespedActionPerformed

    private void btnActualizarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarHuespedActionPerformed
        // TODO add your handling code here:
        actualizarHuesped();
    }//GEN-LAST:event_btnActualizarHuespedActionPerformed

    private void btnEliminarHuespedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarHuespedActionPerformed
        // TODO add your handling code here:
        eliminarHuesped();
    }//GEN-LAST:event_btnEliminarHuespedActionPerformed

    private void btnAsignarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAsignarHabitacionActionPerformed
        // TODO add your handling code here:
        asignarHabitacion();
    }//GEN-LAST:event_btnAsignarHabitacionActionPerformed

    private void btnCancelarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarHabitacionActionPerformed
        // TODO add your handling code here:
        cancelarHabitacion();
    }//GEN-LAST:event_btnCancelarHabitacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizarHuesped;
    private javax.swing.JButton btnAsignarHabitacion;
    private javax.swing.JButton btnBuscarHuesped;
    private javax.swing.JButton btnCancelarHabitacion;
    private javax.swing.JButton btnCrearHuesped;
    private javax.swing.JButton btnEliminarHuesped;
    private javax.swing.JComboBox<String> cbxAnioNacimientoHuesped;
    private javax.swing.JComboBox<String> cbxDiaNacimientoHuesped;
    private javax.swing.JComboBox<String> cbxHabitaciones;
    private javax.swing.JComboBox<String> cbxHuespedes;
    private javax.swing.JComboBox<String> cbxMesNacimientoHuesped;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblAnioNacimientoHuesped;
    private javax.swing.JLabel lblApellidoHuesped;
    private javax.swing.JLabel lblDiaNacimientoHuesped;
    private javax.swing.JLabel lblDocumentoHuesped;
    private javax.swing.JLabel lblEmailHuesped;
    private javax.swing.JLabel lblFechaNacimientoHuesped;
    private javax.swing.JLabel lblHabitacionDisponible;
    private javax.swing.JLabel lblHuespedes;
    private javax.swing.JLabel lblMesNacimientoHuesped;
    private javax.swing.JLabel lblNacionalidadHuesped;
    private javax.swing.JLabel lblNombreHuesped;
    private javax.swing.JLabel lblNumeroHabitacion;
    private javax.swing.JLabel lblTituloPrincipal;
    private javax.swing.JPanel pnlHabitaciones;
    private javax.swing.JPanel pnlHuespedes;
    private javax.swing.JTabbedPane pnlPrincipal;
    private javax.swing.JPanel pnlReservas;
    private javax.swing.JTextField txtApellidoHuesped;
    private javax.swing.JTextField txtDocumentoHuesped;
    private javax.swing.JTextField txtEmailHuesped;
    private javax.swing.JTextField txtHabitacionDisponible;
    private javax.swing.JTextField txtNacionalidadHuesped;
    private javax.swing.JTextField txtNombreHuesped;
    // End of variables declaration//GEN-END:variables

    public boolean validarCamposHuesped() {
        if (txtDocumentoHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El documento es obligatorio");
            return false;
        } else if (txtNombreHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El nombre es obligatorio");
            return false;
        } else if (txtEmailHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El correo es obligatorio");
            return false;
        } else if (txtApellidoHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "El apellido es obligatorio");
            return false;
        } else if (txtNacionalidadHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "La nacionalidad es obligatoria");
            return false;
        } else {
            return true;
        }
    }

    private void crearHuesped() {
        if (validarCamposHuesped()) {

            String documento = txtDocumentoHuesped.getText();
            String nombre = txtNombreHuesped.getText();
            String apellido = txtApellidoHuesped.getText();
            String email = txtEmailHuesped.getText();
            String nacionalidad = txtNacionalidadHuesped.getText();
            int diaNacimiento = Integer.parseInt(cbxDiaNacimientoHuesped.getSelectedItem().toString());
            int mesNacimiento = Integer.parseInt(cbxMesNacimientoHuesped.getSelectedItem().toString());
            int anioNacimiento = Integer.parseInt(cbxAnioNacimientoHuesped.getSelectedItem().toString());

            Huesped huesped
                    = Ctrhuespedes.crearHuesped(documento, nombre, apellido, email,
                            nacionalidad, diaNacimiento, mesNacimiento, anioNacimiento);

            if (huesped != null) {
                JOptionPane.showMessageDialog(this, "Cliente creado correctamente...");
                System.out.println(huesped.getDocumento() + " - " + huesped.getNombre());
                limpiarCamposHuesped();

            } else {
                JOptionPane.showMessageDialog(this, "Error al crear el cliente... Puede que ya exista.");
            }
        }

    }

    private void limpiarCamposHuesped() {
        txtDocumentoHuesped.setText("");
        txtNombreHuesped.setText("");
        txtEmailHuesped.setText("");
        txtApellidoHuesped.setText("");
        txtNacionalidadHuesped.setText("");
        cbxDiaNacimientoHuesped.setSelectedIndex(0);
        cbxMesNacimientoHuesped.setSelectedIndex(0);
        cbxAnioNacimientoHuesped.setSelectedIndex(0);
    }

    private void llenarCombos() {
        for (int i = 1; i <= 31; i++) {
            cbxDiaNacimientoHuesped.addItem(i + "");
        }
        for (int i = 1; i <= 12; i++) {
            cbxMesNacimientoHuesped.addItem(i + "");
        }
        for (int i = LocalDate.now().getYear(); i >= 1940; i--) {
            cbxAnioNacimientoHuesped.addItem(i + "");
        }
    }

    private void buscarHuesped() {
        if (txtDocumentoHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el documento a buscar.", "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        Huesped huesped = Ctrhuespedes.buscarHuesped(txtDocumentoHuesped.getText());
        if (huesped != null) {
            txtNombreHuesped.setText(huesped.getNombre());
            txtApellidoHuesped.setText(huesped.getApellido());
            txtEmailHuesped.setText(huesped.getEmail());
            txtNacionalidadHuesped.setText(huesped.getNacionalidad());
            cbxDiaNacimientoHuesped.setSelectedItem(String.valueOf(huesped.getFechaNacimiento().getDayOfMonth()));
            cbxMesNacimientoHuesped.setSelectedItem(String.valueOf(huesped.getFechaNacimiento().getMonthValue()));
            cbxAnioNacimientoHuesped.setSelectedItem(String.valueOf(huesped.getFechaNacimiento().getYear()));
        } else {
            JOptionPane.showMessageDialog(this, "El huésped no existe.", "No encontrado", JOptionPane.WARNING_MESSAGE);
        }
    }

    private void actualizarHuesped() {

        if (validarCamposHuesped()) {
            boolean actualizado = Ctrhuespedes.actualizarHuesped(
                    txtDocumentoHuesped.getText(),
                    txtNombreHuesped.getText(),
                    txtApellidoHuesped.getText(),
                    txtEmailHuesped.getText(),
                    txtNacionalidadHuesped.getText(),
                    Integer.parseInt(cbxDiaNacimientoHuesped.getSelectedItem().toString()),
                    Integer.parseInt(cbxMesNacimientoHuesped.getSelectedItem().toString()),
                    Integer.parseInt(cbxAnioNacimientoHuesped.getSelectedItem().toString()));
            if (actualizado) {
                JOptionPane.showMessageDialog(this, "Huésped actualizado correctamente.");
                limpiarCamposHuesped();
            } else {
                JOptionPane.showMessageDialog(this, "El huésped no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void eliminarHuesped() {

        if (txtDocumentoHuesped.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Ingrese el documento a eliminar.", "Campo requerido", JOptionPane.WARNING_MESSAGE);
            return;
        }
        int confirmar = JOptionPane.showConfirmDialog(this,
                "¿Está seguro de eliminar el huésped " + txtDocumentoHuesped.getText() + "?",
                "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            boolean eliminado = Ctrhuespedes.borrarHuesped(txtDocumentoHuesped.getText());
            if (eliminado) {
                JOptionPane.showMessageDialog(this, "Huésped eliminado correctamente.");
                limpiarCamposHuesped();
            } else {
                JOptionPane.showMessageDialog(this, "El huésped no existe.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    }

    private void actualizarCbxHabitaciones() {
        cbxHabitaciones.removeAllItems();
        for (Habitacion hab : Ctrhabitaciones.getHabitacionesDisponibles()) {
            cbxHabitaciones.addItem(
                    "Hab. " + hab.getNumero() + " - " + hab.getTipo()
                    + " - $" + hab.getPrecioPorNoche());
        }
    }

    private int getNumeroHabitacionSeleccionada() {
        String seleccion = cbxHabitaciones.getSelectedItem().toString();
        String[] partes = seleccion.split(" ");
        return Integer.parseInt(partes[1]);
    }

    private void actualizarCbxHuespedes() {
        cbxHuespedes.removeAllItems();
        for (Huesped h : Ctrhuespedes.getHotel().getLstHuespedes()) {
            cbxHuespedes.addItem(h.getDocumento() + " - " + h.getNombre() + " " + h.getApellido());
        }
    }

    private void asignarHabitacion() {
        if (cbxHuespedes.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "No hay huéspedes registrados.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }
    if (cbxHabitaciones.getSelectedItem() == null) {
        JOptionPane.showMessageDialog(this, "No hay habitaciones disponibles.", "Advertencia", JOptionPane.WARNING_MESSAGE);
        return;
    }

    int numHab = getNumeroHabitacionSeleccionada();
    String seleccionHuesped = cbxHuespedes.getSelectedItem().toString();
    String documento = seleccionHuesped.split(" - ")[0];
    Huesped huesped = Ctrhuespedes.buscarHuesped(documento);
    String nombreCompleto = huesped.getNombre() + " " + huesped.getApellido();

    Ctrhabitaciones.asignarHuesped(numHab, nombreCompleto);
    actualizarCbxHabitaciones();
    actualizarTablaHabitaciones();

    JOptionPane.showMessageDialog(this,
        "Habitación " + numHab + " asignada correctamente a " + nombreCompleto + ".",
        "Asignación exitosa", JOptionPane.INFORMATION_MESSAGE);
    }

    private void cancelarHabitacion() {
        String numStr = txtHabitacionDisponible.getText().trim();
    if (numStr.equals("")) {
        JOptionPane.showMessageDialog(this, "Ingrese el número de habitación a liberar.", "Campo requerido", JOptionPane.WARNING_MESSAGE);
        return;
    }
    try {
        int numHab = Integer.parseInt(numStr);
        int confirmar = JOptionPane.showConfirmDialog(this,
            "¿Está seguro de liberar la habitación " + numHab + "?",
            "Confirmar", JOptionPane.YES_NO_OPTION);
        if (confirmar == JOptionPane.YES_OPTION) {
            boolean ok = Ctrhabitaciones.liberarHabitacion(numHab);
            if (ok) {
                JOptionPane.showMessageDialog(this, "Habitación " + numHab + " liberada correctamente.");
                actualizarCbxHabitaciones();
                actualizarTablaHabitaciones();
                txtHabitacionDisponible.setText("");
            } else {
                JOptionPane.showMessageDialog(this, "Habitación no encontrada.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "El número debe ser un entero.", "Error", JOptionPane.ERROR_MESSAGE);
    }
    }

    private void actualizarTablaHabitaciones() {
        String[] columnas = {"Número", "Tipo", "Piso", "Precio/Noche", "Huésped Asignado"};
    javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(columnas, 0);

    for (Habitacion hab : Ctrhuespedes.getHotel().getLstHabitaciones()) {
        if (!hab.isDisponible()) {
            String huesped = Ctrhabitaciones.getAsignaciones().getOrDefault(hab.getNumero(), "Sin asignar");
            modelo.addRow(new Object[]{
                hab.getNumero(),
                hab.getTipo(),
                hab.getPiso(),
                "$" + hab.getPrecioPorNoche(),
                huesped
            });
        }
    }
    jTable1.setModel(modelo);
    }

}
